### ISSUE TITLE
Please include TM_PROJECT_DIRECTORY/ dirname of TM_FILEPATH

### ISSUE THREAD

**Issue by perplexes** [briancollins/nice_find#11]
Could you take into account where in the project tree I have selected, or the directory of the file I'm working on? This would make the searches blazing fast for small folders. (Maybe have a select box for "search in (dir)", "search in project", etc, that defaults to your context.)

Thanks!!

**Comment by briancollins** [comment]
you mean if you have vendor highlighted in your project drawer then only search in vendor like ack does?

**Comment by perplexes** [comment]
Exactly - I was actually just trying to find a helper function in my helpers dir, and ended up searching the whole project (which is ~12k files) :)

**Comment by briancollins** [comment]
add an option to search only in selected folder. closed by a0e222bc5952c550bb8752f95d50d6ae737561eb
