### ISSUE TITLE
Grep bombs on 10.5

### ISSUE THREAD

**Issue by adamv** [briancollins/nice_find#13]
Process:         grep [17829]
Path:            /Users/adamv/Library/Application Support/TextMate/PlugIns/NiceFind.tmplugin/Contents/Resources/grep
Identifier:      grep
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  TextMate [17823]

Interval Since Last Report:          531787 sec
Crashes Since Last Report:           7
Per-App Interval Since Last Report:  0 sec
Per-App Crashes Since Last Report:   1

Date/Time:       2009-10-30 16:49:55.172 -0700
OS Version:      Mac OS X 10.5.8 (9L30)
Report Version:  6
Anonymous UUID:  960DF2C4-68E9-43B3-8F98-D9541B0B7540

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000
Crashed Thread:  0

Dyld Error Message:
  unknown required load command 0x80000022

**Comment by briancollins** [comment]
Yes I stupidly built it for 10.6 only. Any idea what the macports flags are to build for 10.5?

**Comment by adamv** [comment]
I dunno, I use Homebrew to install stuff these days: http://github.com/mxcl/homebrew
But doesn't grep come for free with OS X? I have it in /usr/bin/grep
What version are you building?

**Comment by briancollins** [comment]
I included a grep 2.5.4 binary because OS X grep doesn't support --exclude-dir and --exclude only works on filenames

**Comment by garrytan** [comment]
Hm this bug causes nice_find to be totally broken for Leopard.

**Comment by briancollins** [comment]
If someone compiles grep 2.5.4 in 10.5 I will gladly include it. I have no access to Leopard so I can't.

**Comment by adamv** [comment]
I've added a brew formula for GNU Grep 2.5.4 that works on my 10.5 box:

http://github.com/adamv/homebrew/commit/7dd58934935d8063b468a36b9951117243758d04

I'd suggest that nice_find look for and use a TM_GREP env var, and use that instead of the pack-in grep if provided.

**Comment by briancollins** [comment]
Thanks for this, I don't have 10.5 to compile but I will update to honor TM_GREP and also fall back on system grep if Res/grep fails.
