### ISSUE TITLE
search with git-grep always returns 0 results

### ISSUE THREAD

**Issue by jerodsanto** [briancollins/nice_find#14]
Regular search (case-sensitive & non-sensitive) returns results as expected. Enable git-grep and it returns 0 every time.

I'm on 10.6 with git 1.6.4.4 (not sure if git version matters)

**Comment by briancollins** [comment]
see issue #12.

**Comment by jerodsanto** [comment]
I saw issue #12 but it says that git-grep fails when case-insensitive search is enabled. I am reporting that git-grep ALWAYS returns 0 results no matter which options are enabled (case-sensitive, case-insensitive, regex, no regex).

**Comment by briancollins** [comment]
Try the latest download

**Comment by jerodsanto** [comment]
I'm on the latest

**Comment by briancollins** [comment]
the folder you're searching has to be a git repository and the git repository has to have tracked files. what does "git grep" from the command line in the same folder return?

**Comment by jerodsanto** [comment]
"git grep" returns 2 results and nice_find returns 0 results. Any other information I can provide to further diagnose this?

I'm perusing your source & have built with success. I can make small changes and test if it'd help out.

**Comment by briancollins** [comment]
Are you on snow leopard?

**Comment by triplef** [comment]
Same problem here, on Snow Leopard 10.6.1, with the following exception when checking "Use git-grep":
`TextMate[23985]    Exception raised during posting of notification.  Ignored.  exception: '*** -[NSConcreteFileHandle fileDescriptor]: No such file or directory'  invoked observer method: '*** -[FindController getData:]'  observer: 0x5e2120  notification name: 'NSFileHandleReadCompletionNotification'`

**Comment by sho** [comment]
Confirming both the initial report and triplef's console message above. Git grep run from terminal provides correct results, nice_find in git mode always returns 0. Normal grep mode works as expected.

**Comment by jerodsanto** [comment]
Make sure that your git executable is in a default path that TextMate can find. For instance, mine is in /opt/local/bin and nice_find was returning 0 results. Then I symlinked that to /sbin and it works again.

```
sudo ln -s /opt/local/bin/git /sbin/git
```
