### ISSUE TITLE
Wrong Download Version

### ISSUE THREAD

**Issue by jerodsanto** [briancollins/nice_find#15]
The Downloads page says it is version 2.1, but when I go to install it says version 1.8. Building from source creates version 2.1 so I'm assuming you accidentally uploaded an older build?

**Comment by briancollins** [comment]
This was a github issue, they seem to be serving the old file if I upload a new one with the same filename. I have changed the filename and it works now, thanks.

**Comment by jerodsanto** [comment]
right on
