### ISSUE TITLE
Subsequent searches do not update resultsTable

### ISSUE THREAD

**Issue by jerodsanto** [briancollins/nice_find#16]
First result shows in resultsTable, but if you change a flag (eg - disable case-sensitivity) and run search again it will not refresh the resultsTable. The results count refreshes just fine, however.

**Comment by briancollins** [comment]
see issue #12.

**Comment by jerodsanto** [comment]
How is this related to #12? This has to do with the resultsTable's content only getting set once and then never refreshing on subsequent searches. This is regardless of which search flags are set.

Like I said, the results count in the bottom-left updates but the actual content of the resultsTable does not. Can you not reproduce this?

**Comment by briancollins** [comment]
no I can't but you're right it is not related to #12, I just saw the case sensitivity change and assumed. But presumably you're not using git-grep so it can't be
