### ISSUE TITLE
nice_find can't find git if not in a standard path

### ISSUE THREAD

**Issue by briancollins** [briancollins/nice_find#17]
for example if you have it installed through macports. Strangely I don't have this problem. Symlinking in /usr/sbin or wherever is a workaround

**Comment by adamv** [comment]
nice_find should honor the "TM_GIT" env. variable, if set.

**Comment by briancollins** [comment]
That could work. Is TM_GIT the full path to git? e.g. /opt/local/bin/git

**Comment by briancollins** [comment]
honor TM_GIT path. closed by d768ba37dd6c0eb4a6c26ea1f1bbd210eef051d3
