### ISSUE TITLE
"Look in selected folder" won't open results

### ISSUE THREAD

**Issue by ghost** [briancollins/nice_find#19]
When I search in a folder, and double click on a result, it opens a new, blank window (with the title of the file, I assume it's a path issue). It should open a tab with the file in the project I'm working on. This does not happen when I un-check "Look in selected folder".

Also, thank you for making this. :)

**Comment by briancollins** [comment]
this is a regression but should be simple to fix, thanks

**Comment by briancollins** [comment]
fix opening selected regression. closed by 70f884bd2ccc85191ba5b1173e6e6961ffa9bfab
