### ISSUE TITLE
nice_find doesn’t use "find clipboard"

### ISSUE THREAD

**Issue by triplef** [briancollins/nice_find#20]
Usually any find panel uses a special clipboard containing the last string searched for. This can also be set using the Cmd-E keyboard shortcut ("Use selection for find"). Unfortunately nice_find doesn’t seem to use that.
See [NSFindPboard in NSPasteboard](http://developer.apple.com/mac/library/documentation/Cocoa/Reference/ApplicationKit/Classes/NSPasteboard_Class/Reference/Reference.html#//apple_ref/doc/c_ref/NSFindPboard) for details.

**Comment by briancollins** [comment]
Oh nice I didn't know about that. Will add

**Comment by triplef** [comment]
Awesome, thanks!

**Comment by briancollins** [comment]
update pasteboard if changed. thanks svenax. closed by 169467b53a8af6627d0c01b7f1b59a9c10abe818.
