### ISSUE TITLE
Textmate chokes when viewing a single file

### ISSUE THREAD

**Issue by fakingfantastic** [briancollins/nice_find#26]
Hey man, let me start out first by thanking you for whipping up an awesome product. 

Here's a quick thing I found: if you open a single file (not a folder) or if you create a new file (cmd+n), and do cmd+shift+f, the native find in project shows up, and it freezes textmate causing you to do a process kill. Why you need to do find in project in a single file? You wouldn't, so I figured it may be something a simple if(SINGLE_FILE) could fix. I'd help, but Obj-C scares me.

Happy coding

**Comment by rsms** [comment]
Here's a sample trace of TextMate — seems you/TM intercept a notification which in turn causes the same notification to be triggered, causing an infinite loop.

http://hunch.se/tmp/nice_find_TextMate_sample.txt
