### ISSUE TITLE
Does not ignore contents of .svn directories

### ISSUE THREAD

**Issue by eppsilon** [briancollins/nice_find#3]
Nice plugin!  Only issue I've had so far is that if my project contains .svn directories I get results for files in them.

**Comment by briancollins** [comment]
thanks, do you think maybe it should ignore all hidden files?

**Comment by eppsilon** [comment]
I'm not sure...if that's what TextMate's default search does, then I think that would be fine.

**Comment by briancollins** [comment]
add grep triple-universal-binary with support for --exclude-dir. exclude .svn, .git. closed by a3fb484f0678330d1f7e7649f94aa8951d6dbb8e
