### ISSUE TITLE
Searches in removed folders

### ISSUE THREAD

**Issue by stiang** [briancollins/nice_find#4]
Whenever I fire up a Rails project, I remove references to the doc, log and tmp folders in the project drawer, to speed up project searches and avoid unnecessary results. However, nice_find searches the entire project, even folders that have been removed. It would be better (and more in line with the built-in find in project) if nice_find searched only the folders/files in the project drawer.

**Comment by briancollins** [comment]
I'm gonna close this because it falls under the same problem as #6
