### ISSUE TITLE
nice find window opens wherever it originally was (even in another space)

### ISSUE THREAD

**Issue by jerodsanto** [briancollins/nice_find#5]
If you have a couple of projects (folders) open in TM at the same time you can only search the first one you opened. Subsequent launches of the plugin set focus on the first project, even if its in another Space.

To reproduce:

1)  open a TextMate window on a folder
2)  cmd+shift+f - run a search
3)  open a second TextMate window on a separate folder (keep original folder open)
4)  cmd+shift+f

**Comment by briancollins** [comment]
Just tested and it works. Changes earlier may have fixed this.

**Comment by jerodsanto** [comment]
I tested with current version and this still occurs. Perhaps I explained it improperly:

The second "Find in Project" that you run performs the search on the correct TM project (as expected), but the "Find in Project" _window_ is placed on top of the first TM project you ran it in, even if your current TM project is on the other side of the desktop or even in another Space.

Using this with Spaces is the most dramatic example as hitting cmd+shift+f will actually move you from your current Space to the Space where your first TM project is.

Does that make more sense?

**Comment by briancollins** [comment]
That makes sense, will look tonight

**Comment by briancollins** [comment]
position relative to opening window and remember last position for each opening window. should provide spaces and multi-monitor support. closed by 6b5bd715ec98d3f998536e0becd5096edac0d5e9

**Comment by briancollins** [comment]
Hmm that didn't fix it for spaces.

**Comment by briancollins** [comment]
open find panel in current space. closed by 29d7df0ca42df2808eaf28b35919621fda686b00

**Comment by jerodsanto** [comment]
WooHoo! Thanks!!
