### ISSUE TITLE
After find, TM pegs both CPUs

### ISSUE THREAD

**Issue by perplexes** [briancollins/nice_find#7]
Everything is normal, then I search, it shows results, and BAM! TM process is pegging both of my processors. Here is a sample of the process, if it helps you: http://gist.github.com/220652

**Comment by george** [comment]
I'm experiencing the same issue.  The searches were quick and working well, but I had to uninstall the plug in due to this issue

**Comment by briancollins** [comment]
thanks for the stack trace I will check it out tonight

**Comment by briancollins** [comment]
Can't reproduce this on any of my projects. Can you give an example of say a github project that has this problem?

**Comment by perplexes** [comment]
Any git project I have. It looks like it's spawning _tons_ of threads, even after bringing back the result. I've got TM 1.5.8 (1509), OS X 10.5.8. I'll try with a clean install of TM at some point.

**Comment by briancollins** [comment]
Can you try the version I just uploaded?

**Comment by perplexes** [comment]
That fixes it! Rockin.

**Comment by briancollins** [comment]
Awesome

**Comment by george** [comment]
The new drop is working for me, too.  Thanks for the quick fix.
