### ISSUE TITLE
I don't want to double click.

### ISSUE THREAD

**Issue by perplexes** [briancollins/nice_find#9]
When I single-click on a result, I would like it to take me to the relevant line, not double click. There's nothing "extra" to do when I select the result with a single click, right? So halve my clicking effort! :D

**Comment by briancollins** [comment]
It's pretty unexpected in a table view, the default behaviour in XCode find and every other table view is for double clicks. Maybe a single clickable icon at the end of the table like in itunes or hotkeys 1-9 for the first 9 results. Anyway I'm closing this for now.

**Comment by perplexes** [comment]
It was worth a shot. ;)
